CREATE TABLE [dbo].[LongTodo] (
	[Id] int IDENTITY(1, 1) NOT NULL,
	[Content] TEXT COLLATE Hungarian_CI_AS NULL,
	[IsActive] nvarchar(255) COLLATE Hungarian_CI_AS NOT NULL,
	CONSTRAINT [PK_LONGTODO_ID] PRIMARY KEY NONCLUSTERED ([Id])
)

CREATE TABLE [dbo].[ShortTodo] (
	[Id] int IDENTITY(1, 1) NOT NULL,
	[Content] TEXT COLLATE Hungarian_CI_AS NULL,
	[IsActive] nvarchar(255) COLLATE Hungarian_CI_AS NOT NULL,
	CONSTRAINT [PK_SHORTTODO_ID] PRIMARY KEY NONCLUSTERED ([Id])
)

CREATE TABLE [dbo].[ArchiveTodo] (
	[Id] int IDENTITY(1, 1) NOT NULL,
	[Content] TEXT COLLATE Hungarian_CI_AS NULL,
	[IsActive] nvarchar(255) COLLATE Hungarian_CI_AS NOT NULL,
	CONSTRAINT [PK_ARCHIVETODO_ID] PRIMARY KEY NONCLUSTERED ([Id])
)